void *ReallocatePool ( uintptr_t OldSize, uintptr_t NewSize, void *OldBuffer );
void *ReallocateRuntimePool ( uintptr_t OldSize, uintptr_t NewSize, void *OldBuffer );
void *ReallocateReservedPool ( uintptr_t OldSize, uintptr_t NewSize, void *OldBuffer );
void g_free (gpointer ptr);
gchar * g_strfreev(const gchar **str_array);
gpointer g_malloc0_n (gsize n_blocks, gsize n_block_bytes);
gpointer g_malloc (gsize n_bytes);
gpointer g_malloc0 (gsize n_bytes);
gpointer g_malloc_n (gsize n_blocks, gsize n_block_bytes);
gpointer g_try_malloc0_n (gsize n_blocks, gsize n_block_bytes);
gpointer g_try_malloc (gsize n_bytes);
gpointer g_try_malloc0 (gsize n_bytes);
gpointer g_try_malloc_n (gsize n_blocks, gsize n_block_bytes);
gpointer g_realloc(gpointer mem, gsize n_bytes);
gpointer g_try_realloc(gpointer mem, gsize n_bytes);
gpointer g_realloc_n(gpointer mem, gsize n_blocks, gsize n_block_bytes);
gpointer g_try_realloc_n(gpointer mem, gsize n_blocks, gsize n_block_bytes);
void *kcalloc(size_t n, size_t size, gfp_t flags);
void *kmalloc_array(size_t n, size_t size, gfp_t flags);
void *kzalloc_node(size_t size, gfp_t flags, int node);
void *kmalloc(size_t size, gfp_t flags);
void *kzalloc(size_t size, gfp_t flags);
void *__kmalloc(size_t size, gfp_t flags);
void *__kmalloc_node(size_t size, gfp_t flags, int node);
void kfree(const void *x);
void kzfree(const void *x);
void *vmalloc(unsigned long size);
void vfree(const void *addr);
void *vrealloc(void *ptr, size_t size);
struct input_dev *input_allocate_device(void);
void input_free_device(struct input_dev *dev);
struct platform_device *platform_device_alloc(const char *name, int id);
void rfkill_alloc(struct rfkill *rfkill, bool blocked);
struct workqueue_struct *create_freezable_workqueue(void *name);
struct tty_driver *alloc_tty_driver(int lines);
struct tty_driver *__alloc_tty_driver(int lines);
void freeaddrinfo(struct addrinfo *res);
void *OEM_Malloc(uint32 uSize);
void *aee_malloc(uint32 dwSize);
void aee_free(void *p);
void *OEM_Realloc(void *p, uint32 uSize);
void *aee_realloc(void *p, uint32 dwSize);
char *__alloc_some_string(void);
void *__get_nonfreeable(void);
void *__get_nonfreeable_tainted(void);
void *__get_nonfreeable_possible_null(void);
void *__get_nonfreeable_tainted_possible_null(void);
void *__get_nonfreeable_not_null(void);
char *__get_nonfreeable_string(void);
char *__get_nonfreeable_possible_null_string(void);
char *__get_nonfreeable_not_null_string(void);
char *__get_nonfreeable_tainted_possible_null_string(void);
void sqlite3_free_table(char **result);
void *__malloc(sqlite3_int64 size);
void *sqlite3_malloc(int size);
void *sqlite3_malloc64(sqlite3_uint64 size);
void *__realloc(void *ptr, sqlite3_uint64 size);
void *sqlite3_realloc(void *ptr, int size);
void *sqlite3_realloc64(void *ptr, sqlite3_uint64 size);
void sqlite3_free(void *ptr);
void sqlite3_value_free(sqlite3_value *pVal);
sqlite3_mutex *sqlite3_mutex_alloc(int id);
void sqlite3_mutex_free(sqlite3_mutex *p);
void sqlite3_snapshot_free(sqlite3_snapshot *pSnapshot);
void *calloc(size_t num, size_t size);
void free(void *ptr);
void *malloc(size_t size);
void *aligned_alloc(size_t alignment, size_t size);
void *realloc(void *ptr, size_t size);
