char *crypt(const char *key, const char *salt);
char *crypt_r(const char *key, const char *salt, struct crypt_data *data);
void setkey(const char *key);
void setkey_r(const char *key, struct crypt_data *data);
int ecb_crypt(char *key, char *data, unsigned datalen, unsigned mode);
int cbc_crypt(char *key, char *data, unsigned datalen, unsigned mode, char *ivec);
void des_setparity(char *key);
void passwd2des(char *passwd, char *key);
int xencrypt(char *secret, char *passwd);
int xdecrypt(char *secret, char *passwd);
